import { useMemo } from 'react';
import type { components } from '../types/api';
import { useApiList } from './useApi';

export type Event = components['schemas']['Event'];
export type EventListResponse = components['schemas']['EventListResponse'];
export type EventRule = components['schemas']['EventRule'];
export type EventRuleListResponse = components['schemas']['EventRuleListResponse'];
export type Silence = components['schemas']['Silence'];
export type SilenceListResponse = components['schemas']['SilenceListResponse'];
export type Resource = components['schemas']['Resource'];
export type ResourceListResponse = components['schemas']['ResourceListResponse'];
export type ResourceGroup = components['schemas']['ResourceGroup'];
export type ResourceGroupListResponse = components['schemas']['ResourceGroupListResponse'];
export type TopologyView = components['schemas']['TopologyView'];
export type TopologyListResponse = components['schemas']['TopologyListResponse'];
export type Dashboard = components['schemas']['Dashboard'];
export type DashboardListResponse = components['schemas']['DashboardListResponse'];
export type Insight = components['schemas']['Insight'];
export type InsightListResponse = components['schemas']['InsightListResponse'];
export type WarRoom = components['schemas']['WarRoom'];
export type WarRoomListResponse = components['schemas']['WarRoomListResponse'];
export type Script = components['schemas']['Script'];
export type ScriptListResponse = components['schemas']['ScriptListResponse'];
export type Schedule = components['schemas']['Schedule'];
export type ScheduleListResponse = components['schemas']['ScheduleListResponse'];
export type Execution = components['schemas']['Execution'];
export type ExecutionListResponse = components['schemas']['ExecutionListResponse'];
export type NotificationPolicy = components['schemas']['NotificationPolicy'];
export type NotificationPolicyListResponse = components['schemas']['NotificationPolicyListResponse'];
export type NotificationChannel = components['schemas']['NotificationChannel'];
export type NotificationChannelListResponse = components['schemas']['NotificationChannelListResponse'];
export type NotificationRecord = components['schemas']['NotificationRecord'];
export type NotificationHistoryListResponse = components['schemas']['NotificationHistoryListResponse'];
export type Label = components['schemas']['Label'];
export type LabelListResponse = components['schemas']['LabelListResponse'];
export type MailSetting = components['schemas']['MailSetting'];
export type MailSettingListResponse = components['schemas']['MailSettingListResponse'];
export type AuthSetting = components['schemas']['AuthSetting'];
export type AuthSettingListResponse = components['schemas']['AuthSettingListResponse'];
export type UserProfile = components['schemas']['UserProfile'];
export type UserPreference = components['schemas']['UserPreference'];
export type UserProfileListResponse = components['schemas']['UserProfileListResponse'];
export type UserPreferenceListResponse = components['schemas']['UserPreferenceListResponse'];

export const useEvents = () => useApiList<EventListResponse>('/events');
export const useEventRules = () => useApiList<EventRuleListResponse>('/event-rules');
export const useSilences = () => useApiList<SilenceListResponse>('/silences');
export const useResources = () => useApiList<ResourceListResponse>('/resources');
export const useResourceGroups = () => useApiList<ResourceGroupListResponse>('/resource-groups');
export const useTopologies = () => useApiList<TopologyListResponse>('/topology');
export const useDashboards = () => useApiList<DashboardListResponse>('/dashboards');
export const useInsights = () => useApiList<InsightListResponse>('/insights');
export const useWarRoomDashboards = () => useApiList<WarRoomListResponse>('/war-room');
export const useScripts = () => useApiList<ScriptListResponse>('/scripts');
export const useSchedules = () => useApiList<ScheduleListResponse>('/schedules');
export const useExecutions = () => useApiList<ExecutionListResponse>('/executions');
export const useNotificationPolicies = () => useApiList<NotificationPolicyListResponse>('/notification-policies');
export const useNotificationChannels = () => useApiList<NotificationChannelListResponse>('/channels');
export const useNotificationHistory = () => useApiList<NotificationHistoryListResponse>('/notifications');
export const useLabels = () => useApiList<LabelListResponse>('/labels');
export const useMailSettings = () => useApiList<MailSettingListResponse>('/mail-settings');
export const useAuthSettings = () => useApiList<AuthSettingListResponse>('/auth-settings');

export const useProfile = () => {
  const response = useApiList<UserProfileListResponse>('/profile');
  const profile = useMemo(() => response.data?.items?.[0] ?? null, [response.data]);
  return { ...response, data: profile as UserProfile | null };
};

export const usePreferences = () => {
  const response = useApiList<UserPreferenceListResponse>('/preferences');
  const preference = useMemo(() => response.data?.items?.[0] ?? null, [response.data]);
  return { ...response, data: preference as UserPreference | null };
};
