// 頁面組件統一導出
export { default as LoginPage } from './LoginPage'
export { default as SREWarRoomPage } from './SREWarRoomPage'
export { default as IncidentsPage } from './IncidentsPage'
export { default as SilenceRulePage } from './SilenceRulePage'
export { default as EventRulePage } from './EventRulePage'
export { default as ResourcesPage } from './ResourcesPage'
export { default as ResourceGroupPage } from './ResourceGroupPage'
export { default as ResourceTopologyPage } from './ResourceTopologyPage'
export { default as DashboardPage } from './DashboardPage'
export { default as DashboardViewPage } from './DashboardViewPage'
export { default as AnalyzingPage } from './AnalyzingPage'
export { default as AutomationPage } from './AutomationPage'
export { default as IdentitySettingsPage } from './IdentitySettingsPage'
export { default as NotificationSettingsPage } from './NotificationSettingsPage'
export { default as PlatformSettingsPage } from './PlatformSettingsPage'
export { default as ProfilePage } from './ProfilePage'
export { default as SREInfrastructureInsightPage } from './SREInfrastructureInsightPage'